### ISSUE TITLE
Welcoming Problem Solvers For Hacktober Fest 🔥🔥

### ISSUE THREAD

**Issue by shreyanshchordia** [shreyanshchordia/Graph_Algorithms#1]
1. **Star** the Repository 
2. **Fork** it 
3. **Contribute** your code  
4. Issue a **PULL REQUEST**  

Contribution of new code to this repository needs to be done in a specific manner otherwise your Pull Requests will be invalid. Kindly check README.md file to understand how exactly contribution can be done to the repository.

**Comment by amishaagarwal1998** [comment]
I want to create a folder for Topological sort and add various algo for the same. Can I proceed?

**Comment by shreyanshchordia** [comment]
@amishaagarwal1998 go for it !!!

**Comment by Mayankjha997** [comment]
I want to add rock , paper and scissor game in c language ,can I add ?

**Comment by NidhiNivedita6** [comment]
Can I add Newton Raphson Method in C?

**Comment by shreyanshchordia** [comment]
Code must be on Graph Algorithm. Check out the README.md for more

**Comment by shivam2001pandey** [comment]
@shreyanshchordia I have added 'Alien Dictionary' (Hard ) which is solved using topological sorting .
kindly have a look into it and please merge it.
Thank You.

**Comment by shivam2001pandey** [comment]
Thank you for merging it. Will it be counted toward Hactoberfest Contest (hactoberfest-accepted tag) ?

**Comment by shreyanshchordia** [comment]
@shivam2001pandey mostly yes. It is counted. Go and check once on the hacktober fest website, to see your progress. If it shows this repository under review then it's accepted. If not then let me know.
